baseurl = "/"
languageCode = "en-us"
title = "w://"

[params]
  description = "Um futuro Master Chef"

[[menu.main]]
    name = "Quem sou"
    url  = "/queum-sou"
    weight = 1

[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 2
